### ISSUE TITLE
Link wird nicht angezeigt

### ISSUE THREAD

**Issue by StefanDumont** [correspSearch/csLink#11]
Ein Link zum Brief, obwohl in den Daten vorhanden, wird nicht angezeigt. Siehe Beispiel hier: https://schnitzler-tagebuch.acdh.oeaw.ac.at/pages/show.html?document=entry__1909-12-01.xml# ("Briefeditionen vernetzen" ist unten in der Mitte). 

Der erste Brief (Beer-Hofmann, Richard an Schnitzler, Arthur, 30.11.1909) wird nicht verlinkt, obwohl in den JSON-Daten (Stand jetzt) der Link korrekt hinterlegt ist. Der zweite Brief "Bahr, Hermann an Schnitzler, Arthur, [Königsberg/Kalinigrad], 02.12.1909" ist korrekt verlinkt. Einziger Unterschied der Links - soweit ich sehen kann - ist, neben der Domain, das der nicht-funktionierende gesichert ist (https).

**Comment by S0bi** [comment]
Bug wurde behoben. Aktueller Stand befindet sich auf dem dev-Branch
