### ISSUE TITLE
Text nicht konfigurierbar

### ISSUE THREAD

**Issue by SanjaSaric** [correspSearch/csLink#43]
Es wäre wirklich super, wenn der Text konfigurierbar wäre oder es zumindest eine Möglichkeit gäbe, eine andere Sprache als Deutsch auszusuchen. Wenn man eine nicht-deutsche oder mehrsprachige Webseite hat, ist es nicht besonders sinnvoll, wenn der Linktext "Briefnetz erkunden" und das eingeblendete Fenster auf Deutsch sind.

**Comment by StefanDumont** [comment]
Ja, da hast du natürlich völlig recht. Danke für das Feedback, wir werden schauen, dass wir das im nächsten Release berücksichtigen.

**Comment by S0bi** [comment]
Es gibt jetzt die Möglichkeit die Sprache auf Englisch zu stellen. Dazu wurde ein neues Attribut "data-language" hinzugefügt. Mit "en" wird der Text auf Englisch gestellt.

**Comment by S0bi** [comment]
Das Update befindet sich auf dem dev-Branch
