### ISSUE TITLE
Angezeigte Briefe werden nicht korrekt ausgewählt

### ISSUE THREAD

**Issue by StefanDumont** [correspSearch/csLink#46]
Wenn ich keinen Fehler bei mir übersehen habe, dann wählt csLink die angezeigten Briefe aus der Treffermenge falsch aus. Er holt die Briefe vom Anfang der Treffermenge, sollte aber unmittelbar um den Zeitpunkt herum die Briefe anzeigen (`before-after` in der Konfiguration.

Konfiguration im div-Snippet vor Javascript-Ausführung:

```
<div id="csLink" 
    data-correspondent-1-name="Alexander von Humboldt"
    data-correspondent-1-id="http://d-nb.info/gnd/118554700"
    data-correspondent-2-name="Samuel Thomas von Soemmerring"
    data-correspondent-2-id="http://d-nb.info/gnd/118805193" 
    data-start-date="1793-12-05"
    data-end-date="" 
    data-exclude-edition="#AVHR" 
    data-range="30" 
    data-selection-when="before-after"
    data-selection-span="median-before-after" 
    data-result-max="4" 
    data-language="de"/>
```

Siehe auch: https://edition-humboldt.de/H0002655, Brief ist vom 5.12.1793, er zeigt Briefe von Anfang November an, obwohl es entsprechende Briefe um den 5.12. herum gibt.

**Comment by S0bi** [comment]
Im Code muss noch abgedeckt werden, was passiert wenn kein selectionSpan angegeben ist. Z.B. Wenn nur ein Datum angegeben ist, dann dieses Datum wählen, bei zwei Daten median berechnen.

**Comment by S0bi** [comment]
Der oben genannte Fall wurde abgedeckt und die Suche nach den Brieftreffern wurde auch optimiert.

**Comment by StefanDumont** [comment]
Implemented in v2.0.
